// App action types
export const APP_LOADING = 'APP_LOADING';
export const LOADING_SUCCESS = 'LOADING_SUCCESS';
export const APP_ERRORS = 'APP_ERRORS';

// Database action types
export const DATABASE_UPDATING = 'DATABASE_UPDATING';
export const DATABASE_UPDATED = 'DATABASE_UPDATED';

// Alert action types
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

// Auth action types
export const LOAD_USER_ACCOUNT = 'LOAD_USER_ACCOUNT';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_ACCOUNT = 'LOGOUT_ACCOUNT';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const AUTH_ERROR = 'AUTH_ERROR';

// User action types
export const CHANGE_THEME = 'CHANGE_THEME';
export const UPDATE_USER_DETAILS = 'UPDATE_USER_DETAILS';
export const UPDATE_ACCOUNT_SETTINGS = 'UPDATE_ACCOUNT_SETTINGS';
export const UPDATE_USER_PASSWORD = 'UPDATE_USER_PASSWORD';
export const SET_DEVICE_INFO = 'SET_DEVICE_INFO';
export const DELETE_USER = 'DELETE_USER';
export const TOGGLE_ACCOUNT_DISABLED = 'TOGGLE_ACCOUNT_DISABLED';
export const SEND_SUPPORT_MESSAGE = 'SEND_SUPPORT_MESSAGE';
export const SUBMIT_BUG_REPORT = 'SUBMIT_BUG_REPORT';
export const USER_VIEWED_PROMOTION = 'VIEWED_PROMOTION';
export const USER_USED_PROMOTION = 'USER_USED_PROMOTION';
export const USER_UNUSED_PROMOTION = 'USER_USED_PROMOTION';

// Promotions action types
export const LOAD_USER_PROMOTIONS = 'LOAD_USER_PROMOTIONS';
export const FILTER_PROMOTIONS = 'FILTER_PROMOTIONS';
