export const SET_ALERT = 'SET_ALERT'
export const REMOVE_ALERT = 'REMOVE_ALERT'

// App interface reducers
export const TOGGLE_SIDE_NAV = 'TOGGLE_SIDE_NAV'
export const LOADING = 'LOADING'
export const ERRORS = 'ERRORS'
export const SUCCESS = 'SUCCESS'

// Map reducers
export const GET_ADDRESS = 'GET_ADDRESS'
export const GET_COORDINATES = 'GET_COORDINATES'
export const MAP_ERROR = 'MAP_ERROR'
export const MAP_LOADING = 'MAP_LOADING'
export const MAP_LOADED = 'MAP_LOADED'

// Auth reducers
export const LOGOUT_ACCOUNT = 'LOGOUT_ACCOUNT'
export const LOAD_ACCOUNT = 'LOAD_ACCOUNT'
export const AUTH_ERROR = 'AUTH_ERROR'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const GET_ALL_COMPANIES = 'GET_ALL_COMPANIES'

// Access Groups
export const CREATE_ACCESS_GROUP = 'CREATE_ACCESS_GROUP'
export const REMOVE_ACCESS_GROUPS = 'REMOVE_ACCESS_GROUP'
export const UPDATE_ACCESS_GROUP = 'UPDATE_ACCESS_GROUP'
export const GET_ACCESS_GROUPS = 'GET_ACCESS_GROUPS'
export const ACCESS_GROUP_ERROR = 'ACCESS_GROUP_ERROR'

// Stores
export const GET_STORES = 'GET_STORES'
export const REMOVE_STORES = 'REMOVE_STORES'
export const UPDATE_STORE = 'UPDATE_STORE'
export const CREATE_STORE = 'CREATE_STORE'
export const STORE_ERROR = 'STORE_ERROR'

// Products
export const PRODUCT_GROUPS_LOADING = 'PRODUCT_GROUPS_LOADING'
export const PRODUCTS_LOADING = 'PRODUCTS_LOADING'
export const GET_PRODUCT_GROUPS = 'GET_PRODUCT_GROUPS'
export const REMOVE_PRODUCT_GROUPS = 'REMOVE_PRODUCT_GROUPS'
export const UPDATE_PRODUCT_GROUP = 'UPDATE_PRODUCT_GROUP'
export const CREATE_PRODUCT_GROUP = 'CREATE_PRODUCT_GROUP'
export const REMOVE_PRODUCTS = 'REMOVE_PRODUCTS'
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT'
export const PRODUCT_ERROR = 'PRODUCT_ERROR'
export const PRODUCT_GROUP_ERROR = 'PRODUCT_GROUP_ERROR'

// Promotions
export const PROMOTIONS_LOADING = 'PROMOTIONS_LOADING'
export const GET_PROMO_GROUPS = 'GET_PROMO_GROUPS'
export const CREATE_PROMO_GROUP = 'CREATE_PROMO_GROUP'
export const UPDATE_PROMO_GROUP = 'UPDATE_PROMO_GROUP'
export const REMOVE_PROMO_GROUP = 'REMOVE_PROMO_GROUP'
export const REMOVE_PROMOTIONS = 'REMOVE_PROMOTIONS'
export const SET_PROMO_GROUP_STATUS = 'SET_PROMO_GROUP_STATUS'
export const LINK_PROMO_GROUP = 'LINK_PROMO_GROUP'
export const UNLINK_PROMO_GROUP = 'UNLINK_PROMO_GROUP'
export const GENERATE_BUNDLE_PROMOTIONS = 'GENERATE_BUNDLE_PROMOTIONS'
export const GENERATE_DISCOUNT_PROMOTIONS = 'GENERATE_DISCOUNT_PROMOTIONS'
export const GENERATE_BOGOFF_PROMOTIONS = 'GENERATE_BOGOFF_PROMOTIONS'
export const PROMO_GROUP_ERROR = 'PROMO_GROUP_ERROR'
export const PROMOTIONS_ERROR = 'PROMOTIONS_ERROR'
